### ISSUE TITLE
I am not getting emails every month

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/automated_annotation#9]
We are supposed to get an email report every month detailing if there are organisms with missing annotations. Although the settings form has been configured correctly, I am still not getting an email.

My cron entry:
```bash
0 2 1 * * cd /var/www/html & drush annotations-check;
```

**Comment by bradfordcondon** [comment]
is the mail logger module enabled?  You can use that to confirm the mails were sent or not.

**Comment by almasaeed2010** [comment]
Just got the email when I ran it manually so I guess it is a cron issue

**Comment by almasaeed2010** [comment]
The crontab entry had `&` instead of `&&`. That's the whole issue.
